name: Build

run-name: Build pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Compile-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          git clone https://github.com/pybind/pybind11.git
          cd pybind11
          cmake -B build -S .
          cmake --build build
          cmake --install build
          $env:Path += ";C:/Program Files (x86)/pybind11/share/cmake/pybind11/"
          cd ..
          choco install python313 python312 python311 python310 python39
          cd package
          C:\ProgramData\chocolatey\bin\python3.13.exe -m venv .py313-env
          .py313-env\Scripts\activate
          pip install build pybind11
          python -m build
          C:\ProgramData\chocolatey\bin\python3.12.exe -m venv .py312-env
          .py312-env\Scripts\activate
          pip install build pybind11
          python -m build
          C:\ProgramData\chocolatey\bin\python3.11.exe -m venv .py311-env
          .py311-env\Scripts\activate
          pip install build pybind11
          python -m build
          C:\ProgramData\chocolatey\bin\python3.10.exe -m venv .py310-env
          .py310-env\Scripts\activate
          pip install build pybind11
          python -m build
          C:\ProgramData\chocolatey\bin\python3.9.exe -m venv .py39-env
          .py39-env\Scripts\activate
          pip install build pybind11
          python -m build

      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: |
            package/dist

  Compile-MacOS:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          brew install cmake pybind11 python@3.13 python@3.12 python@3.11 python@3.10 python@3.9
          python3.13 -m venv .py313-env
          python3.12 -m venv .py312-env
          python3.11 -m venv .py311-env
          python3.10 -m venv .py310-env
          python3.9 -m venv .py39-env
          source .py313-env/bin/activate
          pip3 install build
          ./build.sh
          source .py312-env/bin/activate
          pip3 install build
          ./build.sh
          source .py311-env/bin/activate
          pip3 install build
          ./build.sh
          source .py310-env/bin/activate
          pip3 install build
          ./build.sh
          source .py39-env/bin/activate
          pip3 install build
          ./build.sh

      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64
          path: |
            package/dist
