name: Build

run-name: Build pipeline triggered by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Compile-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          choco install python313
          C:\ProgramData\chocolatey\bin\python3.13.exe --version

      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64
          path: |
            dist

  Compile-MacOS:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          brew install cmake pybind11 python@3.13 python@3.12 python@3.11 python@3.10 python@3.9
          python3.13 -m venv .py313-env
          python3.12 -m venv .py312-env
          python3.11 -m venv .py311-env
          python3.10 -m venv .py310-env
          python3.9 -m venv .py39-env
          source .py313-env/bin/activate
          pip3 install build
          ./build.sh
          source .py312-env/bin/activate
          pip3 install build
          ./build.sh
          source .py311-env/bin/activate
          pip3 install build
          ./build.sh
          source .py310-env/bin/activate
          pip3 install build
          ./build.sh
          source .py39-env/bin/activate
          pip3 install build
          ./build.sh

      - name: Archive compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-arm64
          path: |
            package/dist
